name: matrix Demo
on:
  push:
    branches:
      - main
jobs:
  matrixbranch:
    strategy:
      matrix:
        operation-system: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.operation-system}}
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
      - name: build app
        run: npm run build
