name: reusable yaml
on:
  workflow_call:
    inputs:
      artifact-name:
        description: this takes artifact as input
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: output of reusable workflow_call
        value: ${{jobs.deploy.outputs.outcome}}
jobs:
  deploy:
    outputs:
      outcome: ${{steps.stepout.outputs.stepoutcome}}
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}
      - name: check folder content
        run: ls
      - name: store output result
        id: stepout
        run: echo "stepoutcome=success" >> $GITHUB_OUTPUT ';'
      - name: deploy app
        run: echo "deploying the app"
